name: deploy on push
on: [push]

jobs:
  deploy-app:
    run-on: ubuntu-latest
    steps:
      - name: check out the code to build the server
        uses: actions/checkout@v3
      - name: copy file to server
        uses: appleboy/scp-action@master
        with: 
          host: ${{secrets.HOST}}
          username: ${{secrets.SSH_USER_NAME}}
          port: ${{secrets.SSH_PORT}}
          key: ${{secrets.SSH_KEY}}
          source: "./html/*"
          target: "/var/www/html"
          strips_components: 1